### ISSUE TITLE
Unable to import 'pandas'

### ISSUE THREAD

**Issue by Neutronttech** [unforgiventr/Kavi-Voice-Assistant#7]
Unable to import 'pandas'

**Comment by DoDzilla-ai** [comment]
.Pandas kütüphanesi eksik. `pip3 install pandas` ile çözülebilir. 

Not: Eski bir soru olduğunun farkındayım. Başkalar daı faydalansın diye yazıyorum. Pandas kütüphanesi README'de belirtilmemiş ancak projede kullanılmış. Bunun da kurulması gerekli.
